---
- name: K8s Token
  debug:
    msg: "k8sMasterToken {{ hostvars['k8s100']['k8sMasterToken'] }}"

- name: Setp bridge forwarding
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name:  Clear Kube
  block:
  - name: kubeadm reset
    command: kubeadm reset -f

  - name: Clear cni network
    command: ip link delete cni0
    ignore_errors: yes

  - name: Clear flannel network
    command: ip link delete flannel.1
    ignore_errors: yes

  - name: Clear CNI
    file:
      state: absent
      path: /etc/cni/net.d
  when: kubeAdmReset

- name: Join cluster
  command: "kubeadm join 192.168.2.100:6443 --token {{ hostvars['k8s100']['k8sMasterToken'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['k8s100']['k8sMasterCa'] }}"
