- name: Set Config
  set_fact:
    targetDir: /opt/gateway

- name: Python venv tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3-pip
    - python-setuptools # Needed for ansible to switch to python3
    - virtualenv

- name: Copy Gateway files
  copy:
    src: python
    dest: "{{ targetDir }}"

- name: Install Gateway app
  pip:
    name: "{{ targetDir }}/python"
    # requirements: "{{ targetDir }}/http/requirements.txt"
    virtualenv: "{{ targetDir }}/venv"
    virtualenv_python: python3.7
    # virtualenv_command: python3 -m venv

- name: Gateway Systemd
  copy:
    src: systemd/gateway.service
    dest: /etc/systemd/system/


