---
- hosts: k8s
  vars:
    kubeAdmReset: false
    # k8sAdminUser: k8sadmin
    # ansible_user: ansible
    # ansible_become: yes
    # vlan_interface: eth0
    # vlan_tag: "3"
    # nfs_exports:
    #   - /nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)
    #   - /tftpboot *(rw,sync,no_subtree_check,no_root_squash)
  roles:
  # - users
  # - k8s-all
- hosts: k8s100
  vars:
    k8sAdminUser: k8sadmin
  roles:
  - k8s-master
- hosts: k8s102
  roles:
  - k8s-worker
- hosts: k8s101
  roles:
  - k8s-worker
    #- example
    # - nfs-server
    # - vlan
    # - dnsmasq
    # - router
    #- initrd
    # - piCore
    # - dietpiclient
    # - gatewayserver
    # - firmware
