---
- hosts: gateway
  vars:
    ansible_user: ansible
    ansible_become: yes
    vlan_interface: eth0
    vlan_tag: "3"
    nfs_exports:
      - /nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)
      - /tftpboot *(rw,sync,no_subtree_check,no_root_squash)
  roles:
    - nfs-server
    - vlan
    - dnsmasq
