---

- name: init kubeadm
  command: kubeadm init --pod-network-cidr=192.168.100.0/24

- name: Get master token
  command: kubeadm token create # --print-join-command
  register: k8sMasterToken

- name: Get master CA
  shell: |
    openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -pubkey |
    openssl rsa -pubin -outform DER 2>/dev/null |
    sha256sum | cut -d ' ' -f1
  register: k8sMasterCa

- name: kubeconfig dir
  file:
    state: directory
    path: "/home/{{ k8sAdminUser }}/.kube"

- name: kubeconfig file
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ k8sAdminUser }}/.kube/config"
    owner: root
    group: root
    mode: '0755'

# - name: Install Weave Net network driver
#   command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
#   register: weavenet_driver
#   when: false

# - name: Install Flannel network driver
#   command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
#   register: flannel_driver
#   when: kubeadm_init is succeeded

- name: Kubernetes master token
  set_fact:
    k8sMasterToken: "{{ k8sMasterToken.stdout }}"
    k8sMasterCa: "{{ k8sMasterCa.stdout }}"

