---
- name: Docker exists
  command: which docker
  register: docker_exists
  ignore_errors: yes

- name: Docker install
  block:
  - name: Docker Dir
    file:
      path: /opt/docker/scripts
      state: directory
      mode: '0755'

  - name: Download get_docker.sh
    get_url:
      url: https://get.docker.com
      dest: /opt/docker/scripts/get_docker.sh
      mode: '555'

  - name: Run installer
    command: sh /opt/docker/scripts/get_docker.sh
    
  when: docker_exists.failed


