---
#examples: https://gist.github.com/carlosedp/1b72b0d80c960e72f10698e2c95f3f1f
#
#
# - debug: var=ansible_facts

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"

- name: Install Docker
  apt:
    name: "{{packages}}"
    update_cache: yes
  vars:
    packages:
    - docker-ce={{docker_version}}

- name: Create user and add to wheel and docker
  user:
    name: "{{ k8sAdminUser }}"
    groups:
    - wheel
    - docker
    append: yes
    state: present
    createhome: yes

- name: Add ssh keys
  authorized_key:
    user: "{{ k8sAdminUser }}"
    state: present
    key: "{{ lookup('file', '/home/ben.greene/.ssh/id_rsa.pub') }}"

- name: Docker Systemd config
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  register: dockerDaemonFile

- name: Create Docker systemd file 
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  register: dockerSystemdFile

- name: Restart Docker Daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: dockerDaemonFile.changed or dockerSystemdFile.changed

- name: Fetch images
  command: kubeadm config images pull
