---
- name: Install dnsmasq
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - dnsmasq

- name: tftpboot dir
  file:
    path: /tftpboot
    state: directory
    mode: '0755'
  register: tftpbootDir

- name: populate tftpboot
  copy:
    src: /boot/
    dest: /tftpboot
    mode: preserve
  when: tftpbootDir.changed


- name: dnsmasq file
  template:
    src: dnsmasq.j2
    dest: "/etc/dnsmasq.d/{{ vlan_interface }}.{{ vlan_tag }}"
    owner: root
    group: root
    mode: 0644
  notify: reload dnsmasq
 
- name: Ensure dnsmasq is running
  service:
    name: dnsmasq
    state: started

- name: Configure resolve.conf to use dnsmasq dns
  lineinfile:
    path: /etc/dhcp/dhclient.conf
    regexp: '^prepend domain-name-servers.*;'
    line: "prepend domain-name-servers 192.168.2.1;"
    insertafter: '^#supersede domain-name .*;'
