---
- name: Ansible user
  user:
    name: ansible
    comment: Ansible user
    groups:
    - sudo
    - wheel

- name: Ansible authorized key
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/ben.greene/.ssh/id_rsa.pub') }}"

