- name: Restart docker-registry
  systemd:
    name: docker-registry
    daemon_reload: yes
    state: restarted
 
- name: Restart docker-proxy
  systemd:
    name: docker-proxy
    daemon_reload: yes
    state: restarted
 